import type { Course } from "./scheduler-types"

export const sampleCourses: Course[] = [
  {
    id: "cs101",
    code: "CS 101",
    name: "Intro to Computer Science",
    department: "Computer Science",
    credits: 3,
    sections: [
      {
        id: "cs101-a",
        sectionCode: "A",
        instructor: "Dr. Smith",
        slots: [
          { day: "Mon", startHour: 9, endHour: 10.5 },
          { day: "Wed", startHour: 9, endHour: 10.5 },
        ],
        capacity: 40,
        enrolled: 32,
      },
      {
        id: "cs101-b",
        sectionCode: "B",
        instructor: "Dr. Johnson",
        slots: [
          { day: "Tue", startHour: 11, endHour: 12.5 },
          { day: "Thu", startHour: 11, endHour: 12.5 },
        ],
        capacity: 40,
        enrolled: 38,
      },
      {
        id: "cs101-c",
        sectionCode: "C",
        instructor: "Dr. Smith",
        slots: [
          { day: "Mon", startHour: 14, endHour: 15.5 },
          { day: "Wed", startHour: 14, endHour: 15.5 },
        ],
        capacity: 35,
        enrolled: 20,
      },
    ],
  },
  {
    id: "math201",
    code: "MATH 201",
    name: "Calculus II",
    department: "Mathematics",
    credits: 4,
    sections: [
      {
        id: "math201-a",
        sectionCode: "A",
        instructor: "Prof. Lee",
        slots: [
          { day: "Mon", startHour: 8, endHour: 9 },
          { day: "Wed", startHour: 8, endHour: 9 },
          { day: "Fri", startHour: 8, endHour: 9 },
        ],
        capacity: 30,
        enrolled: 28,
      },
      {
        id: "math201-b",
        sectionCode: "B",
        instructor: "Prof. Davis",
        slots: [
          { day: "Tue", startHour: 13, endHour: 14 },
          { day: "Thu", startHour: 13, endHour: 14 },
          { day: "Fri", startHour: 13, endHour: 14 },
        ],
        capacity: 30,
        enrolled: 15,
      },
    ],
  },
  {
    id: "eng102",
    code: "ENG 102",
    name: "English Composition",
    department: "English",
    credits: 3,
    sections: [
      {
        id: "eng102-a",
        sectionCode: "A",
        instructor: "Dr. Brown",
        slots: [{ day: "Mon", startHour: 11, endHour: 12.5 }],
        capacity: 25,
        enrolled: 22,
      },
      {
        id: "eng102-b",
        sectionCode: "B",
        instructor: "Dr. Wilson",
        slots: [{ day: "Wed", startHour: 15, endHour: 16.5 }],
        capacity: 25,
        enrolled: 10,
      },
      {
        id: "eng102-c",
        sectionCode: "C",
        instructor: "Dr. Brown",
        slots: [{ day: "Fri", startHour: 10, endHour: 11.5 }],
        capacity: 25,
        enrolled: 18,
      },
    ],
  },
  {
    id: "phys150",
    code: "PHYS 150",
    name: "General Physics I",
    department: "Physics",
    credits: 4,
    sections: [
      {
        id: "phys150-a",
        sectionCode: "A",
        instructor: "Prof. Chen",
        slots: [
          { day: "Tue", startHour: 9, endHour: 10.5 },
          { day: "Thu", startHour: 9, endHour: 10.5 },
        ],
        capacity: 35,
        enrolled: 30,
      },
      {
        id: "phys150-b",
        sectionCode: "B",
        instructor: "Prof. Martinez",
        slots: [
          { day: "Mon", startHour: 15.5, endHour: 17 },
          { day: "Wed", startHour: 15.5, endHour: 17 },
        ],
        capacity: 35,
        enrolled: 12,
      },
    ],
  },
  {
    id: "hist101",
    code: "HIST 101",
    name: "World History",
    department: "History",
    credits: 3,
    sections: [
      {
        id: "hist101-a",
        sectionCode: "A",
        instructor: "Dr. Patel",
        slots: [
          { day: "Tue", startHour: 14, endHour: 15.5 },
          { day: "Thu", startHour: 14, endHour: 15.5 },
        ],
        capacity: 50,
        enrolled: 42,
      },
      {
        id: "hist101-b",
        sectionCode: "B",
        instructor: "Dr. Garcia",
        slots: [
          { day: "Mon", startHour: 11, endHour: 12.5 },
          { day: "Wed", startHour: 11, endHour: 12.5 },
        ],
        capacity: 50,
        enrolled: 35,
      },
    ],
  },
  {
    id: "chem110",
    code: "CHEM 110",
    name: "General Chemistry",
    department: "Chemistry",
    credits: 4,
    sections: [
      {
        id: "chem110-a",
        sectionCode: "A",
        instructor: "Dr. Kim",
        slots: [
          { day: "Mon", startHour: 13, endHour: 14 },
          { day: "Wed", startHour: 13, endHour: 14 },
          { day: "Fri", startHour: 13, endHour: 14 },
        ],
        capacity: 40,
        enrolled: 36,
      },
      {
        id: "chem110-b",
        sectionCode: "B",
        instructor: "Dr. Taylor",
        slots: [
          { day: "Tue", startHour: 16, endHour: 17 },
          { day: "Thu", startHour: 16, endHour: 17 },
          { day: "Fri", startHour: 16, endHour: 17 },
        ],
        capacity: 40,
        enrolled: 22,
      },
    ],
  },
  {
    id: "psych100",
    code: "PSYCH 100",
    name: "Intro to Psychology",
    department: "Psychology",
    credits: 3,
    sections: [
      {
        id: "psych100-a",
        sectionCode: "A",
        instructor: "Prof. Adams",
        slots: [
          { day: "Mon", startHour: 10, endHour: 11 },
          { day: "Wed", startHour: 10, endHour: 11 },
        ],
        capacity: 60,
        enrolled: 55,
      },
      {
        id: "psych100-b",
        sectionCode: "B",
        instructor: "Prof. Adams",
        slots: [
          { day: "Tue", startHour: 15.5, endHour: 16.5 },
          { day: "Thu", startHour: 15.5, endHour: 16.5 },
        ],
        capacity: 60,
        enrolled: 30,
      },
    ],
  },
  {
    id: "art120",
    code: "ART 120",
    name: "Drawing Fundamentals",
    department: "Art",
    credits: 3,
    sections: [
      {
        id: "art120-a",
        sectionCode: "A",
        instructor: "Prof. Rivera",
        slots: [{ day: "Tue", startHour: 10, endHour: 12.5 }],
        capacity: 20,
        enrolled: 18,
      },
      {
        id: "art120-b",
        sectionCode: "B",
        instructor: "Prof. Rivera",
        slots: [{ day: "Thu", startHour: 10, endHour: 12.5 }],
        capacity: 20,
        enrolled: 8,
      },
    ],
  },
  {
    id: "econ200",
    code: "ECON 200",
    name: "Microeconomics",
    department: "Economics",
    credits: 3,
    sections: [
      {
        id: "econ200-a",
        sectionCode: "A",
        instructor: "Dr. Nguyen",
        slots: [
          { day: "Mon", startHour: 16, endHour: 17.5 },
          { day: "Wed", startHour: 16, endHour: 17.5 },
        ],
        capacity: 45,
        enrolled: 40,
      },
      {
        id: "econ200-b",
        sectionCode: "B",
        instructor: "Dr. White",
        slots: [
          { day: "Tue", startHour: 8, endHour: 9.5 },
          { day: "Thu", startHour: 8, endHour: 9.5 },
        ],
        capacity: 45,
        enrolled: 25,
      },
    ],
  },
  {
    id: "phil101",
    code: "PHIL 101",
    name: "Intro to Philosophy",
    department: "Philosophy",
    credits: 3,
    sections: [
      {
        id: "phil101-a",
        sectionCode: "A",
        instructor: "Dr. Morgan",
        slots: [{ day: "Fri", startHour: 11, endHour: 13 }],
        capacity: 35,
        enrolled: 28,
      },
      {
        id: "phil101-b",
        sectionCode: "B",
        instructor: "Dr. Clark",
        slots: [
          { day: "Tue", startHour: 17, endHour: 18 },
          { day: "Thu", startHour: 17, endHour: 18 },
        ],
        capacity: 35,
        enrolled: 15,
      },
    ],
  },
]