// constants.ts

export interface Subject {
    label: string;
    value: string;
  }
  
  export const SUBJECTS: Subject[] = [
    { value: 'ACCT', label: 'Accounting' },
    { value: 'AGRON', label: 'Agronomy' },
    { value: 'ARTID', label: 'Interior Design' },
    { value: 'BIOL', label: 'Biology' },
    { value: 'CJ', label: 'Criminal Justice' },
    { value: 'CLSCI', label: 'Climate Science' },
    { value: 'CLST', label: 'Classical Studies' },
    { value: 'CONE', label: 'Construction Engineering' },
    { value: 'ECON', label: 'Economics' },
    { value: 'EDUC', label: 'Education' },
    { value: 'ENGR', label: 'Engineering' },
    { value: 'ENTSP', label: 'Entrepreneurship' },
    { value: 'ENVS', label: 'Environmental Studies' },
    { value: 'FIN', label: 'Finance' },
    { value: 'FSHN', label: 'Food Science and Human Nutrition' },
    { value: 'GEN', label: 'Genetics' },
    { value: 'GEOL', label: 'Geology' },
    { value: 'HDFS', label: 'Human Development and Family Studies' },
    { value: 'HIST', label: 'History' },
    { value: 'IE', label: 'Industrial Engineering' },
    { value: 'LING', label: 'Linguistics' },
    { value: 'MATH', label: 'Mathematics' },
    { value: 'MGMT', label: 'Management' },
    { value: 'MICRO', label: 'Microbiology' },
    { value: 'MIS', label: 'Management Information Systems' },
    { value: 'MKT', label: 'Marketing' },
    { value: 'MTEOR', label: 'Meteorology' },
    { value: 'NREM', label: 'Natural Resource Ecology and Management' },
    { value: 'PHIL', label: 'Philosophy' },
    { value: 'PSYCH', label: 'Psychology' },
    { value: 'RELIG', label: 'Religious Studies' },
    { value: 'RUS', label: 'Russian' },
    { value: 'SCM', label: 'Supply Chain Management' },
    { value: 'SOC', label: 'Sociology' },
    { value: 'SPAN', label: 'Spanish' },
    { value: 'SPCM', label: 'Speech Communication' },
    { value: 'USLS', label: 'U.S. Latino/a Studies' },
    { value: 'WGS', label: 'Women\'s and Gender Studies' },
    { value: 'WLC', label: 'World Languages and Cultures' },
    { value: 'ABE', label: 'Agricultural and Biosystems Engineering' },
    { value: 'ADVRT', label: 'Advertising' },
    { value: 'AECL', label: 'Animal Ecology' },
    { value: 'AERE', label: 'Aerospace Engineering' },
    { value: 'AESHM', label: 'Apparel, Events, and Hospitality Management' },
    { value: 'AFAM', label: 'African and African American Studies' },
    { value: 'AGEDS', label: 'Agricultural Education and Studies' },
    { value: 'AMD', label: 'Apparel, Merchandising, and Design' },
    { value: 'AMIN', label: 'American Indian Studies' },
    { value: 'ANS', label: 'Animal Science' },
    { value: 'ANTHR', label: 'Anthropology' },
    { value: 'ARABC', label: 'Arabic' },
    { value: 'ARCH', label: 'Architecture' },
    { value: 'ARTED', label: 'Art Education' },
    { value: 'ARTGR', label: 'Graphic Design' },
    { value: 'ARTH', label: 'Art History' },
    { value: 'ARTIS', label: 'Integrated Studio Arts' },
    { value: 'ASTRO', label: 'Astronomy and Astrophysics' },
    { value: 'ATR', label: 'Athletic Training' },
    { value: 'BBMB', label: 'Biochemistry, Biophysics, and Molecular Biology' },
    { value: 'BCB', label: 'Bioinformatics and Computational Biology' },
    { value: 'BCBIO', label: 'Bioinformatics and Computational Biology (UG)' },
    { value: 'BME', label: 'Biomedical Engineering' },
    { value: 'BMS', label: 'Biomedical Sciences' },
    { value: 'BPMI', label: 'Biological/Pre-Medical Illustration' },
    { value: 'BUSAD', label: 'Business Administration' },
    { value: 'CE', label: 'Civil Engineering' },
    { value: 'CHE', label: 'Chemical Engineering' },
    { value: 'CHEM', label: 'Chemistry' },
    { value: 'CHIN', label: 'Chinese' },
    { value: 'COMDV', label: 'Community Development' },
    { value: 'COMS', label: 'Computer Science' },
    { value: 'COMST', label: 'Communication Studies' },
    { value: 'CPRE', label: 'Computer Engineering' },
    { value: 'CRP', label: 'Community and Regional Planning' },
    { value: 'CYBSC', label: 'Cyber Security' },
    { value: 'DANCE', label: 'Dance' },
    { value: 'DH', label: 'Digital Health' },
    { value: 'DS', label: 'Data Science' },
    { value: 'DSNS', label: 'Design Studies' },
    { value: 'ECP', label: 'Early Childcare Education and Programming' },
    { value: 'EDADM', label: 'Educational Administration' },
    { value: 'EE', label: 'Electrical Engineering' },
    { value: 'EEB', label: 'Ecology and Evolutionary Biology' },
    { value: 'EEOB', label: 'Ecology, Evolution and Organismal Biology' },
    { value: 'ELPS', label: 'Educational Leadership and Policy Studies' },
    { value: 'EM', label: 'Engineering Mechanics' },
    { value: 'ENGL', label: 'English' },
    { value: 'ENSCI', label: 'Environmental Science' },
    { value: 'ENT', label: 'Entomology' },
    { value: 'ENVE', label: 'Environmental Engineering' },
    { value: 'EVENT', label: 'Event Management' },
    { value: 'FCEDS', label: 'Family and Consumer Sciences Education and Studies' },
    { value: 'FFP', label: 'Family Financial Planning' },
    { value: 'FOR', label: 'Forestry' },
    { value: 'FRNCH', label: 'French' },
    { value: 'GDCB', label: 'Genetics, Development and Cell Biology' },
    { value: 'GENET', label: 'Interdisciplinary' },
    { value: 'GER', label: 'German' },
    { value: 'GERON', label: 'Gerontology' },
    { value: 'GLOBE', label: 'Global Resource Systems' },
    { value: 'GRST', label: 'Graduate Studies' },
    { value: 'HCI', label: 'Human Computer Interaction' },
    { value: 'HCM', label: 'Healthcare Management' },
    { value: 'HGED', label: 'Higher Education' },
    { value: 'HON', label: 'Honors' },
    { value: 'HORT', label: 'Horticulture' },
    { value: 'HS', label: 'Health Studies' },
    { value: 'HSCI', label: 'Human Sciences' },
    { value: 'HSPM', label: 'Hospitality Management' },
    { value: 'IGS', label: 'Interdisciplinary Graduate Studies' },
    { value: 'IMBIO', label: 'Immunobiology' },
    { value: 'INDD', label: 'Industrial Design' },
    { value: 'INTST', label: 'International Studies' },
    { value: 'JLMC', label: 'Journalism and Mass Communication' },
    { value: 'KIN', label: 'Kinesiology' },
    { value: 'LA', label: 'Landscape Architecture' },
    { value: 'LAS', label: 'Liberal Arts and Sciences' },
    { value: 'LDST', label: 'Leadership Studies' },
    { value: 'LIB', label: 'Library' },
    { value: 'MATE', label: 'Materials Engineering' },
    { value: 'MCDB', label: 'Molecular, Cellular, and Developmental Biology' },
    { value: 'ME', label: 'Mechanical Engineering' },
    { value: 'MSE', label: 'Materials Science and Engineering' },
    { value: 'MUSIC', label: 'Music' },
    { value: 'NEURO', label: 'Neuroscience' },
    { value: 'NRS', label: 'Nursing' },
    { value: 'NUTRS', label: 'Nutritional Sciences' },
    { value: 'PERF', label: 'Performing Arts' },
    { value: 'PHYS', label: 'Physics' },
    { value: 'PLBIO', label: 'Plant Biology' },
    { value: 'PLP', label: 'Plant Pathology' },
    { value: 'POLS', label: 'Political Science' },
    { value: 'PR', label: 'Public Relations' },
    { value: 'RESEV', label: 'Research and Evaluation' },
    { value: 'SE', label: 'Software Engineering' },
    { value: 'SPED', label: 'Special Education' },
    { value: 'STAT', label: 'Statistics' },
    { value: 'STB', label: 'Seed Technology and Business' },
    { value: 'SUSAG', label: 'Sustainable Agriculture' },
    { value: 'THTRE', label: 'Theatre' },
    { value: 'TOX', label: 'Toxicology' },
    { value: 'TSM', label: 'Technology Systems Management' },
    { value: 'VCS', label: 'Veterinary Clinical Sciences' },
    { value: 'VDPAM', label: 'Veterinary Diagnostic and Production Animal Medicine' },
    { value: 'VMPM', label: 'Veterinary Microbiology and Preventive Medicine' },
    { value: 'VPTH', label: 'Veterinary Pathology' },
    { value: 'WFS', label: 'World Film Studies' },
    { value: 'YTH', label: 'Youth' },
    { value: 'ACSCI', label: 'Actuarial Science' },
    { value: 'AFAS', label: 'Air Force Aerospace Studies' },
    { value: 'AI', label: 'Artificial Intelligence' },
    { value: 'ART', label: 'Art and Design' },
    { value: 'ASL', label: 'American Sign Language' },
    { value: 'ATH', label: 'Athletics' },
    { value: 'CPS', label: 'Cyber-Physical Systems' },
    { value: 'CYBE', label: 'Cyber Security Engineering' },
    { value: 'DES', label: 'Design' },
    { value: 'ECFP', label: 'Early Childhood and Family Policy' },
    { value: 'FAM', label: 'Family and Community Services' },
    { value: 'FDM', label: 'Fashion Design and Merchandising' },
    { value: 'GAME', label: 'Game Design' },
    { value: 'HHSCI', label: 'Health and Human Sciences' },
    { value: 'IHS', label: 'Integrated Health Sciences' },
    { value: 'LATIN', label: 'Latin' },
    { value: 'LLS', label: 'Learning and Leadership Sciences' },
    { value: 'MS', label: 'Military Science' },
    { value: 'NS', label: 'Naval Science' },
    { value: 'REQR', label: 'Required Registration' },
    { value: 'SCIVZ', label: 'Scientific Illustration and Visualization' },
    { value: 'SMC', label: 'Sports Media and Communication' },
    { value: 'UST', label: 'University Studies' },
    { value: 'UXD', label: 'User Experience Design' },
    { value: 'WFCE', label: 'Wildlife and Fisheries Conservation and Ecology' },
    { value: 'WISE', label: 'Women in Science and Engineering' },
    { value: 'ECPE', label: 'Electrical and Computer Engineering' },
    { value: 'PORT', label: 'Portuguese' },
  ].sort((a, b) => a.label.localeCompare(b.label));